version: "3"
services:
  redis:
    image: "redis"
    ports:
      - 6379:6379

  app:
    build: .
    ports:
      - 3000:8080
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis
    depends_on:
      - redis
